jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      lts-9:
        BUILD: stack
        ARGS: "--resolver lts-9"
      lts-11:
        BUILD: stack
        ARGS: "--resolver lts-11"
      lts-12:
        BUILD: stack
        ARGS: "--resolver lts-12"
      lts-14:
        BUILD: stack
        ARGS: "--resolver lts-14"
    maxParallel: 3
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack $ARGS test --bench --no-run-benchmarks
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
