name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver: [nightly, lts-20, lts-15, lts-14, lts-12, lts-11]
        exclude:
          - os: windows-latest
            resolver: lts-15
          - os: windows-latest
            resolver: nightly
        include:
          - os: ubuntu-latest
            resolver: lts-9
            # problems on macOS and Windows (https://github.com/snoyberg/yaml/pull/216#issuecomment-1585522312)

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Cache dependencies
        if:   ${{ runner.os != 'Windows' }}
          # Andreas Abel, 2023-06-10, switching off caching on Windows since ~/.stack is not the correct path here.
        uses: actions/cache@v3
        with:
          path: ~/.stack
            #NB: This path is not valid on Windows
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
            stack test --bench --no-run-benchmarks --haddock --no-haddock-deps --no-terminal --resolver=${{ matrix.resolver }}
